default:
	@echo "--- Normal compilation ----------------------------------"
	@echo "make normal     produces binary in src/"
	@echo " "
	@echo "--- Cleaning up -----------------------------------------"
	@echo "make clean    recursively clean up subdirs"
	@echo " "
	@echo "--- Normal compilation : windows style ------------------"
	@echo "make windows-normal    procudes binary in src/"
	@echo " "
	@echo "--- Cleaning up : windows style -------------------------"
	@echo "make windows-clean    recursively clean up subdirs"

normal:
	cd src && $(MAKE) normal

clean:
	cd src && $(MAKE) clean

windows-normal:
	cd src && $(MAKE) windows-normal

windows-clean:
	cd src && $(MAKE) windows-clean